### PR TITLE
Add //model/@placement_frame to proposal

### PR DESCRIPTION
**Pull request by azeey**
Resolves https://github.com/osrf/sdformat/issues/335

Preview: http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&branch=model_placement_frame#1-4-4-placement-frame-model-placement_frame-and-include-placement_frame

---
This change is [Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42)

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm_strong: with two small comments

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-:-MHQm-mFAv-E4tQbxzOg:b-m96liw)* status: all files reviewed, 1 unresolved discussion (waiting on @azeey and @scpeters)

___
*[composition/proposal.md, line 478 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHQljZA65eE6S6u6_Pu:-MHQljZA65eE6S6u6_Pv:bjgzx69) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L478)):*
> ```Markdown
> ~~~xml
> <model name="super_model">
>   <model name="table" placement_frame="bottom_left_leg">
> ```

BTW In an example here or in a unittest in code, should we note the interaction between `placement_frame` and `@canonical_link`?

(i.e. they are similarly-scoped aspects, but orthogonal in application... or something less obtuse than that :P)
___
*[composition/proposal.md, line 510 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHQlOnT0dZzWv63Y9_g:-MHQlOnU3mrKc_RjMLhf:b-39d2c9) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L510)):*
> ```Markdown
>   </include>
> </model>
> ~~~
> ```

nit Consider mentioning that we originally thought about just having `//include/placement_frame`, but found it'd be hard to implement w/o it being a proper model attribute.

**Review by scpeters — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42)* status: all files reviewed, 3 unresolved discussions (waiting on @azeey and @EricCousineau-TRI)

___
*[composition/proposal.md, line 484 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHY83g96kplT-2VdMsh:-MHY83g96kplT-2VdMsi:brlbh8y) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L484)):*
> ```Markdown
>       <pose relative_to="bottom_center">0 0 2 0 0 0</pose>
>     </frame>
>     <link name="bottom_left_leg"/>
> ```

I would add a pose offset with non-zero values of x and y translation for this example
___
*[composition/proposal.md, line 486 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHY8Qqe6WPj1x3y4eN4:-MHY8Qqe6WPj1x3y4eN5:b-wdd15o) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L486)):*
> ```Markdown
>     <link name="bottom_left_leg"/>
>   </model>
>   <model name="mug" placement_frame="bottom_center">
> ```

having frames named `bottom_center` in both models makes it a little confusing. we could add some comments clarifying scope, or use different names just for clarity (`center_bottom`?)
___
*[composition/proposal.md, line 510 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHQlOnT0dZzWv63Y9_g:-MHY94Et4roaTwhk2DvR:b-e7w5x5) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L510)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider mentioning that we originally thought about just having `//include/placement_frame`, but found it'd be hard to implement w/o it being a proper model attribute.
</blockquote></details>

this could be an "alternative considered"

**Review by azeey — COMMENTED** [review]
I turned on the spell checker before I pushed and found some typos. Fixed in https://github.com/osrf/sdf_tutorials/commit/f0457c951a0440738819ef445cf5d70be07c3319

> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-:-MI1IuMG1S3wLhccfMW4:bwqmrxz)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @scpeters)

___
*[composition/proposal.md, line 478 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHQljZA65eE6S6u6_Pu:-MI1IQZcBxtMGcl9NG7D:b-jppw4g) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L478)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW In an example here or in a unittest in code, should we note the interaction between `placement_frame` and `@canonical_link`?

(i.e. they are similarly-scoped aspects, but orthogonal in application... or something less obtuse than that :P)
</blockquote></details>

Done. https://github.com/osrf/sdf_tutorials/commit/0fcaee00f5adace740b43ceeb1f9e3ad9e518c0d
___
*[composition/proposal.md, line 484 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHY83g96kplT-2VdMsh:-MI1ISyMEtDg3RckTqun:b-qf6eme) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L484)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

I would add a pose offset with non-zero values of x and y translation for this example
</blockquote></details>

I added a pose to the model in https://github.com/osrf/sdf_tutorials/commit/0fcaee00f5adace740b43ceeb1f9e3ad9e518c0d. Is that what you had in mind?
___
*[composition/proposal.md, line 486 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHY8Qqe6WPj1x3y4eN4:-MI1IWeABtlDjMF9nOqS:bz9jne0) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L486)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

having frames named `bottom_center` in both models makes it a little confusing. we could add some comments clarifying scope, or use different names just for clarity (`center_bottom`?)
</blockquote></details>

I removed `bottom_center` from `table` and used `bottom_left_leg` as the relative_to for specifying `top_center`. https://github.com/osrf/sdf_tutorials/commit/0fcaee00f5adace740b43ceeb1f9e3ad9e518c0d
___
*[composition/proposal.md, line 510 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHQlOnT0dZzWv63Y9_g:-MI1Io7n1NqjNQ7OVqwj:b-jppw4g) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L510)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

this could be an "alternative considered"
</blockquote></details>

Done. https://github.com/osrf/sdf_tutorials/commit/0fcaee00f5adace740b43ceeb1f9e3ad9e518c0d

**Review by scpeters — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42)* status: all files reviewed, 1 unresolved discussion (waiting on @azeey)

___
*[composition/proposal.md, line 484 at r1](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MHY83g96kplT-2VdMsh:-MI1b5E21YQkI8_uwufZ:bb6ywmx) ([raw file](https://github.com/osrf/sdf_tutorials/blob/3fce0832b2008adb99cfb302d88a62193b47273c/composition/proposal.md#L484)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I added a pose to the model in https://github.com/osrf/sdf_tutorials/commit/0fcaee00f5adace740b43ceeb1f9e3ad9e518c0d. Is that what you had in mind?
</blockquote></details>

LGTM
___
*[composition/proposal.md, line 516 at r2](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MI1fhKI1xQcnlYpyygE:-MI1fhKKElzxBz8xmbPR:b-t4s6yq) ([raw file](https://github.com/osrf/sdf_tutorials/blob/f0457c951a0440738819ef445cf5d70be07c3319/composition/proposal.md#L516)):*
> ```Markdown
> will have that pose. This is a very practical means of setting the location of
> models. The `//model/@canonical_link` attribute on the other hand specifies to
> which link the implicit model frame is attached. This does not affect the
> ```

nit: "specifies to which link" -> "specifies the link to which"

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @scpeters)

___
*[composition/proposal.md, line 516 at r2](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-MI1fhKI1xQcnlYpyygE:-MI4VHxv7YpagAjhqthQ:bo7j6of) ([raw file](https://github.com/osrf/sdf_tutorials/blob/f0457c951a0440738819ef445cf5d70be07c3319/composition/proposal.md#L516)):*
<details><summary><i>Previously, scpeters (Steve Peters) wrote…</i></summary><blockquote>

nit: "specifies to which link" -> "specifies the link to which"
</blockquote></details>

Done. https://github.com/osrf/sdf_tutorials/commit/579eb166101072afd135c238d8e0f136fd2ad041

**Review by scpeters — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/osrf/sdf_tutorials/42#-:-MI5C9Wn3K7k_sjmq6yW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
